<?php

/**
 * Wrapper function to support both phptemplate & twig template
 */
function at_theming_render_template($template_file, $variables = array()) {
  $template_type = at_theming_detect_template_type($template_file);
  if ('phptemplate' === $template_type) {
    return theme_render_template($template_file, $variables);
  }
  return \Drupal\at_theming\Twig::render($template_file, $variables);
}

/**
 * Detect template type by file name.
 */
function at_theming_detect_template_type($file_name) {
  $path_info = pathinfo($file_name);

  switch ($path_info['extension']) {
    case 'php':
      return 'phptemplate';
  }

  return 'twig';
}

/**
 * Template without file, only support Twig template for now
 */
function at_theming_render_string_template($string, $variables = array(), $engine = 'twig') {
  $twig = \Drupal\at_theming\Twig::getEnvironment();
  $twig->setLoader(new \Twig_Loader_String());
  return $twig->render($string, $variables);
}

/**
 * Implements hook_block_info()
 */
function at_theming_block_info() {
  return at_id(new \Drupal\at_theming\Hook\BlockInfo())->import();
}

/**
 * Implements hook_block_view
 */
function at_theming_block_view($delta) {
  return at_id(new \Drupal\at_theming\Hook\BlockView($delta))->view();
}
