<?php

use \Drupal\at_theming\EntityTemplate\Config as EntityTemplateConfig;
use \Drupal\at_base\Helper\RenderContent as ContentRender;

/**
 * Implements hook_entity_view_alter()
 */
function at_theming_entity_view_alter(&$build, $entity_type) {
  if ($data = at_id(new EntityTemplateConfig($entity_type, $build['#bundle'], $build['#view_mode']))->get()) {
    $data['variables']  = isset($data['variables']) ? $data['variables'] : array();
    $data['variables'] += array('build' => $build);
    $build = array(
      '#entity_type' => $build['#entity_type'],
      '#bundle' => $build['#bundle'],
      '#view_mode' => $build['#view_mode'],
      '#language' => 'language',
      '#contextual_links ' => !empty($build['#contextual_links']) ? $build['#contextual_links'] : NULL,
      'at_theming' => at_id(new ContentRender($data))->render(),
      '#build' => $build,
    );
  }
}
